# Generated by Django 4.2.6 on 2024-05-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
    ]
