# Generated by Django 4.2.6 on 2024-05-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50)),
                ('laptop', models.CharField(max_length=50)),
            ],
        ),
    ]
